config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :sessions, only: [:create]

  resources :users, :favorites, :locations

  resources :trees do
    resources :favorites
  end




# Some specified custom routes:

  get '/search' => 'trees#search'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get 'trees/search' => 'locations#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :favorites, dependent: :destroy
  has_many :trees, through: :favorites

  # Add handlers to run when creating and saving
  before_create :create_remember_token
  before_save :normalize_fields

  # Validate name:
  validates :name,
    presence: true,
    length: { maximum: 50 }

  # Validate email address:
  validates :email,
    presence: true,
    uniqueness: { case_sensitive: false },
    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  # Secure password features:
  has_secure_password

  # Create a new remember token for a user:
  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  # Hash a token:
  def User.hash(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  def favorite(tree)

      trees << tree

  end

  private

  # Creates a new session token for the user:
  def create_remember_token
    self.remember_token = User.hash(User.new_remember_token)
  end

  # Normalize fields for consistency:
  def normalize_fields
    self.email.downcase!
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  before_action :require_current_user, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to @user
    else
      render :new
    end
  end

  def show

  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to root_path
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation
    )
  end

  def require_current_user
    if !current_user?(@user)
      redirect_to root_path
    end
  end
end

app/views/users/_user_form.html.erb
<% if @user.errors.any? %>
<b>Errors:</b>
<ul>
  <% @user.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>

<div class="new_user_form">
  <%= form_for @user do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :email %>
    <%= f.text_field :email %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.label :password_confirmation, 'Confirm Password' %>
    <%= f.password_field :password_confirmation %>

    <%= f.submit "Submit", id: 'submit' %>
  <% end %>
</div>

app/views/users/edit.html.erb
<h1>Edit User Details<%= @user.name %></h1>
<%= render "user_form" %>

<hr>

<%= form_for @user, method: 'delete' do |f| %>
  <%= f.submit "Delete" %>
<% end %>

<hr>

<%= link_to "Cancel", @user %>

app/views/users/new.html.erb
<h1>Create A New User</h1>
<%= render "user_form" %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= link_to "Edit", edit_user_path(@user) %> Details or Password.</p>

<p>email: <%= @user.email %></p>






<p>my favorites:</p><br>
<div class="map">
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>