config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  resources :sessions, only: [:create]

  resources :users, :favorites, :locations

  resources :trees do
    resources :favorites
  end




# Some specified custom routes:

  get '/search' => 'trees#search'
  get '/signup' => 'users#new'
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'
  get 'trees/search' => 'locations#new'

end

app/models/tree.rb
class Tree < ActiveRecord::Base

  has_many :pictures
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites

# Validate name -- Trees have names:
  validates :name,
    presence: true,
    length: { maximum: 50 }

  # Validate species -- Trees have a species:
  validates :species,
    presence: true,
    length: { maximum: 100 }

# Validate description -- Trees have a description:
  validates :description,
    presence: true,
    length: { maximum: 1000 }

    # Validate image_url -- cannot be too long:
  validates :image_data,
    presence: true,
    length: { maximum: 200 }


  # Validates Tree Latitude-- Low
  validates :latitude, numericality: { greater_than_or_equal_to: -75 }

  # Validates Tree Latitude-- High
  validates :latitude, numericality: { less_than_or_equal_to: 75 }

   # Validates Tree Longitude-- Low
  validates :longitude, numericality: { greater_than_or_equal_to: -175 }

   # Validates Tree Longitude-- High
  validates :longitude, numericality: { less_than_or_equal_to: 175 }

  # Validates Tree Height-- Low
  validates :height, numericality: { greater_than_or_equal_to: 0 }

   # Validates Tree Height-- High
  validates :height, numericality: { less_than_or_equal_to: 1000 }



end

app/controllers/trees_controller.rb
class TreesController < ApplicationController
  before_action :make_map, only: [:index ]
  before_action :find_tree, only: [:show, :edit, :update, :destroy]


  def index
  end

  def new
    @tree = Tree.new
    @picture = Picture.new
  end

  def create
    @tree = Tree.new(tree_params)
    if @tree.save
    redirect_to trees_path
    else
      render :new
    end
  end

  def show
    @favorite = Favorite.new
    location = Array.new
    location << {
      'description' => @tree.location,
      'lng' => @tree.longitude,
      'lat' => @tree.latitude
    }
    @gmaps_json = location.to_json
  end

  def edit
  end

  def update
    @tree.update(tree_params)
    redirect_to @tree
  end

  def destroy
    @tree.destroy
    redirect_to trees_path
  end

  def search
    lower_query = params[:q].downcase
    @trees = Tree.where("lower(name) like '%#{lower_query}%'")
  end

  private #=================================================================================

  def load_tree
    return @tree = Tree.find_by(id: params[:user_id])
  end

  def find_tree
    @tree = Tree.find(params[:id])
  end

  def tree_params
    params.require(:tree).permit(:name, :species, :latitude, :longitude, :description, :height, :image_data)
  end

  def make_map
  #THIS IS THE MAP FOR SHOWING IN INDIVIDUAL TREE PROFILES but build_markers is broken and hanging up.
  #TO RE-ENABLE, recomment 'before' at top. see above.
  #def make_map
   @trees = Tree.all
   @hash = Gmaps4rails.build_markers(@trees) do |tree, marker|
     marker.lat tree.latitude
     marker.lng tree.longitude
    end
  end




end

app/helpers/tree_helper.rb
module TreeHelper


  def current_tree
    @current_tree = trees/params(:id)
  end

end

#NOT USED

app/views/trees/_form.html.erb
<% if @tree.errors.any? %>
<b>Errors:</b>
<ul>
  <% @tree.errors.full_messages.each do |msg| %>
  <li><%= msg %></li>
  <% end %>
</ul>
<% end %>



<div class="new_tree_form">
  <%= form_for [@tree] do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br>

    <%= f.label :species %>
    <%= f.text_field :species %><br>

    <%= f.label :latitude %> (XX.000000)
    <%= f.text_field :latitude %><br>

     <%= f.label :longitude %> (XX.000000)
    <%= f.text_field :longitude %><br>

    <%= f.label :description %>
    <%= f.text_field :description %><br>

    <%= f.label :height_in_feet %>
    <%= f.text_field :height %><br>

    <%= f.label :Enter_image_URL %>
    <%= f.text_field :image_data %><br>

    <%= f.submit "Submit", id: "submit" %>
  <% end %>
</div>

app/views/trees/_tree.html.erb
<%= link_to tree.name, tree %>

<% if logged_in? %>

  <%= form_tag(tree_favorites_path(tree), method: :post) do %>
    <%= submit_tag 'Favorites' %>
  <% end %>

  <%= link_to "Edit Tree", edit_tree_path(tree) %>

  <%= form_for tree, method: 'delete' do |f| %>
    <%= f.submit "Delete Tree", id: "delete-tree-#{tree.id}" %>
  <% end %>

<% end %>

app/views/trees/edit.html.erb
<%= render "form" %>

app/views/trees/index.html.erb
<div class="nav_link">
  <%= link_to "Home Map", root_path %>
</div>
<div class="content">
  <h1>Trees</h1>
    <% @trees.each do |tree| %>
      <ul>
        <li>
          #: <%= tree.id %><br>
          Name: <%= link_to tree.name, tree %><br>
          Description: <%= tree.description %><br>
          Lat: <%= tree.latitude %><br>
          Long: <%= tree.longitude %><br>
          Height: <%= tree.height %> feet<br>
          Species: <%= tree.species %><br>
        </li>
      </ul>
    <% end %>
</div>

app/views/trees/new.html.erb
<%= render "form" %>

app/views/trees/search.html.erb
<h2>Trees Search:</h2>
<ul>
  <% @trees.each do |tree| %>
      <li>
        <%= render partial: 'tree', locals: { tree: tree } %>
      </li>
  <% end %>
</ul>

app/views/trees/show.html.erb
<div class="content">
  <div class="nav_links">
    <%= link_to "All Trees", trees_path %><br>
  </div>

  <h1><%= @tree.name %></h1><br>
  <img src="<%= @tree.image_data %>" width="400px"><br>
  <div class="text_block">
    <p>Description: </p> <%= @tree.description %><br>
  </div>
  <div class="nav_block">
    <% if logged_in? %>
      <%= form_tag(tree_favorites_path(@tree), method: :post) do %>
        <%= submit_tag 'Add to Favorites' %>
      <% end %>
      <a href="<%= @tree.id %>/edit"><button class="input">Edit</button></a>
      <%= form_for @tree, method: 'delete' do |f| %>
        <%= f.submit "Delete Tree", id: "destroy" %>
      <% end %>
    <% end %>
  </div>

</div>